# Generated by Django 4.0.6 on 2022-07-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_jobpoststatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.jobpostactivity', verbose_name='지원서')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.jobpoststatus', verbose_name='채용진행상황')),
            ],
            options={
                'db_table': 'job_post_status_log',
            },
        ),
    ]
